Hw03 is completed
tyougut/hw-otus pull request #3
Opened 2021-07-11 17:39 UTC by tyougut

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-07-13 17:34 UTC, agneum requested changes
Спасибо за выполненное задание. Отличная работа. 
Важно, ещё добавить тесты
Итого: 6 баллов из 10

2021-07-13 17:34 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		return result
Предлагаю возвращать значение без использования промежуточной переменной

2021-07-13 17:34 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		}
Можно делать инкремент без предварительной проверки на существование

2021-07-13 17:34 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	sortedStruct := make([]StringSort, 0, 10)
Capacity лучше выбрать сразу равную размеру мапы - `len(elementsMap)`

2021-07-13 17:34 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	for _, value := range sortedStruct {
Достаточно сделать первые 10 итераций(или меньше, если в итоге меньше элементов)

2021-08-01 13:16 UTC, tyougut commented on hw03_frequency_analysis/top.go
> +	for _, value := range sortedStruct {
поправила

2021-08-01 13:16 UTC, tyougut commented on hw03_frequency_analysis/top.go
> +	sortedStruct := make([]StringSort, 0, 10)
поправила

2021-08-01 13:16 UTC, tyougut commented on hw03_frequency_analysis/top.go
> +		return result
поправила

2021-08-01 13:54 UTC, agneum approved these changes
Спасибо за дополнения в PR. Хорошая работа.
Статус: принято
Итого: 9 баллов из 10

2021-08-01 13:54 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	for _, value := range sortedStruct {
Слайс `sortedStruct` всё ещё перебиратся полностью. В итоге в `sortedSlice` попадают все элементы `sortedStruct`.
Дополнительно отмечу полное дублирование кода заполнения `sortedSlice` и формирования `finalSlice`.

Достаточно определить возвращаемое количество элементов и добавить в итоговый слайс только их.

2021-08-02 09:12 UTC, merged